In [3]:
import numpy as np

a = np.arange(6).reshape(2,3) + 10
arg = np.argsort(a, axis=0)
print(a)
print(arg)

[[10 11 12]
 [13 14 15]]
[[0 0 0]
 [1 1 1]]


In [5]:
from EA import myEA
import EA
import numpy as np

active_windows_index = np.arange(12)

np.random.shuffle(active_windows_index)

start_time = np.random.rand(12) * (EA.TIME_END - EA.TIME_START)
start_time.sort()

start_time[0] = 0

print(start_time)
print(myEA.fill_window(start_time))

[ 0.         11.07440825 12.06925686 16.25207796 20.0950837  21.4810505
 36.19704858 55.7465877  57.62214973 59.79491601 70.71534653 72.0500468 ]
[ 0.         10.07440825 11.07440825 11.07440825 12.06925686 15.25207796
 16.25207796 19.0950837  20.0950837  20.4810505  21.4810505  35.19704858
 36.19704858 54.7465877  55.7465877  56.62214973 57.62214973 58.79491601
 59.79491601 69.71534653 70.71534653 71.0500468  72.0500468  80.        ]


In [6]:
b = np.arange(10)
np.random.shuffle(b)
print(b)
print(np.argmin(b))

[2 3 1 8 4 0 6 7 5 9]
5


In [8]:
import numpy as np
b = np.arange(10)
import bisect
print(b)
print(bisect.bisect_left(b, 0))

[0 1 2 3 4 5 6 7 8 9]
0
