In [21]:
import numpy as np

a = np.arange(6).reshape(2, 3) + 10
arg = np.argsort(a, axis=0)
print(a)
print(arg)

[[10 11 12]
 [13 14 15]]
[[0 0 0]
 [1 1 1]]


In [22]:
from EA import myEA
import EA
import numpy as np

active_windows_index = np.arange(12)

np.random.shuffle(active_windows_index)

start_time = np.random.rand(12) * (EA.TIME_END - EA.TIME_START)
start_time.sort()

start_time[0] = 0

print(start_time)
print(myEA.fill_window(start_time))

[ 0.          2.31105464  8.78055377 18.90261471 30.22466058 43.10879726
 44.84351354 46.20781689 46.73902687 47.6699763  54.06534979 63.0970172 ]
[ 0.          1.31095464  2.31105464  7.78045377  8.78055377 17.90251471
 18.90261471 29.22456058 30.22466058 42.10869726 43.10879726 43.84341354
 44.84351354 45.20771689 46.20781689 46.20781689 46.73902687 46.73902687
 47.6699763  53.06524979 54.06534979 62.0969172  63.0970172  80.        ]


In [23]:
b = np.arange(10)
np.random.shuffle(b)
print(b)
print(np.argmin(b))

[8 6 4 7 0 3 2 1 5 9]
4


In [24]:
import numpy as np

b = np.arange(10)
import bisect

print(b)
print(bisect.bisect_left(b, 0))

[0 1 2 3 4 5 6 7 8 9]
0


In [25]:
import numpy as np

b = np.arange(10)

print(b)
print(b[2:9])
print(b[9:2:-1])

b[3: 6] = b[5:2:-1]

print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8]
[9 8 7 6 5 4 3]
[0 1 2 5 4 3 6 7 8 9]


In [26]:
import numpy as np

b = ["a",
     "b",
     "c",
     "d",
     "e",
     "f",
     "g",
     "h",
     "i",
     "j", ]


class feiji:

    def __le__(self, other):
        return 1

    pass


feijis = [
    feiji(),
    feiji(),
    feiji(),
    feiji(),
    feiji(),
    feiji(),
    feiji(),
    feiji(),
    feiji(),
    feiji(),
]

fitness = np.array([1, 20, 4, 2, 1, 4, 8, 7, 10])

print(fitness)
print(b)

ret1, ret2 = zip(*sorted(zip(fitness, b), key=lambda a: a[0]))

print(ret1)
print(ret2)


[ 1 20  4  2  1  4  8  7 10]
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
(1, 1, 2, 4, 4, 7, 8, 10, 20)
('a', 'e', 'd', 'c', 'f', 'h', 'g', 'i', 'b')


In [40]:
import numpy as np

station_time: np.ndarray[int, float] = -1 * np.ones((12, 2))

for i in range(12):
    for j in range(2):
        station_time[i, j] = - (i + 1) * (j + 1)

print(station_time)
result = sorted(station_time, key=lambda a: a[0])

for i in range(len(result)):
    print(i)

for i, j in result:
    print(i, j)


[[ -1.  -2.]
 [ -2.  -4.]
 [ -3.  -6.]
 [ -4.  -8.]
 [ -5. -10.]
 [ -6. -12.]
 [ -7. -14.]
 [ -8. -16.]
 [ -9. -18.]
 [-10. -20.]
 [-11. -22.]
 [-12. -24.]]
0
1
2
3
4
5
6
7
8
9
10
11
-12.0 -24.0
-11.0 -22.0
-10.0 -20.0
-9.0 -18.0
-8.0 -16.0
-7.0 -14.0
-6.0 -12.0
-5.0 -10.0
-4.0 -8.0
-3.0 -6.0
-2.0 -4.0
-1.0 -2.0
